### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by zSamuulele** [zSamuulele/RealLifeWeather#1]
# To-Do list

- [ ] Add compatibility for more weather services
- [ ] Funny things with particles and entities according to weather and conditions (winds, UV, and other)
- [ ] Server time based on where the server's owner is located
- [ ] Vault Support

Tell us some things
